run:
  timeout: 5m
linters:
  enable:
    - gosimple
    - stylecheck
    - revive #deprecated
    #other deprecated lint libraries: maligned, scopelint, interfacer
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - unused
    - deadcode