name: Create Jira Issue

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/create-jira-issue.yml@main
    with:
      github-team: Terraform-Enterprise
      project: TF
      issue-extra-fields: |
        { "customfield_10091": ["TF-CLI"] }
    secrets: inherit
